### ISSUE TITLE
Research into Intel XEON emissions with different models

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#85]
**What**: Generate some data regarding emissions for the same chip/util across different models.
**Why**: So we can start rigorously comparing data from multiple models
**SoW**:
- [ ]  Generate 3 simple IMPLs that represent 1hrs worth of computation on an Intel Xeon (or some common sku).
- [ ] Have 3 impls, one for low utilization (hovering around 15%), another for medium (hovering around 50%) and one for high (hovering around 90%).
- [ ] Run the impls through the Boavista CPU. Boavizta Cloud and CCF models to see how they rack up.
- [ ] On the cloud and CCF models you need to pick a VM which has the same chip across all 3 clouds.

Deliverable:
- A table that looks somewhat like this:

| Sku                     | Model          | Vendor | 10%   | 50%   | 90%   |
| ----------------------- | -------------- | ------ | ----- | ----- | ----- |
| Intel Xeon (some model) | Boavizta Cloud | GCP    | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | Boavizta Cloud | Azure  | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | Boavizta Cloud | AWS    | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | CCF            | GCP    | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | CCF            | AWS    | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | CCF            | Azure  | X mWh | X mWh | X mWh |
| Intel Xeon (some model) | Bovizta CPU    | ---    | X mWh | X mWh | X mWh |

**Comment by jawache** [comment]
A useful tool to find micro arch from instance type for AWS: https://instances.vantage.sh/

**Comment by jawache** [comment]
As discussed today the CPU we'll be comparing against is XEON Platinum 8259 - Cascade Lake

**Comment by jmcook1186** [comment]
Hi Asim

Here's the table for the Intel Xeon Platinum 8529 (Cascade lake)
Please note that the Boavizta CPU model, passing the processor name (row 2), is falling back to some default values because it doesn't have actual data to use, so this should be considered unreliable and maybe omitted - left it in here so you can make that decision yourself!

| Sku                | Model          | Vendor | CPU energy @ 10% (kwh) | CPU energy @ 50% (kwh) | CPU energy @ 100% (kwh) |
| ------------------ | -------------- | ------ | ---------------------- | ---------------------- | ----------------------- |
| m5n.large          | Boavizta Cloud | AWS    | 0.0222                 | 0.0278                 | 0.0229                  |
| Xeon Platinum 8259 | Bovizta CPU    | n/a    | 0.2500                 | 0.5555                 | 0.8333                  |
| m5n.large          | CCF            | AWS    | 0.0019                 | 0.0046                 | 0.0079                  |
| n2-standard-2      | CCF            | GCP    | 0.0019                 | 0.0043                 | 0.0073                  |
| D2 v4              | CCF            | Azure  | 0.0019                 | 0.0046                 | 0.0079                  |

**Comment by jawache** [comment]
Thanks @jmcook1186 

Running through some back of the napkin calculations, so the TDP of the Intel Xeon Platinum 8529 is about 210W.

If running at 1 hr then that's 210 Wh = 0.21 kWh.

So... given it has 24 cores and 48 threads. At 100% that's about 0.004375 kWh per vCPU per hour running at 100%.

If the m5n.large is a single core/2 vCPU instance then at 100% =~ 0.00875 kWh. Which is close to what it's reporting on the CCF front so that looks good!

The Boavizta Cloud doesn't make a lot of sense to me however. the energy usage isn't going up, in fact it goes down from 50% to 100%! Are you using the Boavizta API or our Boavizta IMP? Could you try the API directly to make sure it's not something wrong with our logic?

For row 2, is this just a name mapping thing - would it work if we entered whatever name they use for "Intel Xeon Cascade Lake"

**Comment by jmcook1186** [comment]
Hi @jawache - thanks for catching the error in the Boavizta Cloud row - the 100% value was a typo, now corrected.

Using the API directly yields very similar values for 10% and 100% utilization, but strangely the result for 50% utilization == result for 100% utilization on the API... (i.e. both 50% and 100% utilization yield a result of 0.0555 kwh).

**Comment by jawache** [comment]
So assigning this for now to @gnanakeethan to

- [ ] Investigate and verify the differences between Boavizta Cloud API vs our Implementation results. 
- [ ] Clarify why Boavizta CPU is returning the above data? Cascade Lake is a very popular chip, if we need to enter a different set of characters the represent cascade lake lets do so.

**Comment by jawache** [comment]
Results

![image](https://github.com/Green-Software-Foundation/ief/assets/897523/da8099df-c7bb-4ff9-b291-f7f924ba043b)

Quite significant differences between models and approached.

My Learnings:
- Mapping chips models -> instance types -> raw data is very challenging. Harder than actually getting the numbers was just figuring out if the models supported certain instance types/chips.
- Each model does something different when they see an instance type/microarch they don't know. CCF underestimates/Boavizta, unsure, confusing numbers.
- The raw data all these models are based off is 2 years old now, modern families of chips are not represented at all which means.

**Comment by jawache** [comment]
Age of data sets is inconsistent.
- Azure, AWS, GCP instance types are inconsistent (from different time period).
- Different granularity for different cloud providers. Some cloud providers, say exactly which chip they are using, others say roughly.
- CCF doesn't recognize new instances.
- Document this heavily, guides - **model guides**.

**Comment by gnanakeethan** [comment]
@jawache I have added documentation specific to the docs/implementations folder on ccf-imp branch with #74

**Comment by jawache** [comment]
Closing and creating a new ticket to discuss what the guides/readme should contain.
